<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elements [
  <!ELEMENT element (name,symbol,protons,electrons,neutrons,mass,valence)>
  <!ATTLIST element number CDATA #REQUIRED>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT symbol (#PCDATA)>
  <!ELEMENT protons (#PCDATA)>
  <!ELEMENT electrons (#PCDATA)>
  <!ELEMENT neutrons (#PCDATA)>
  <!ELEMENT mass (#PCDATA)>
  <!ELEMENT valence (#PCDATA)>
]>
<elements>
    <element number="1">
        <name>Hydrogen</name>
        <symbol>H</symbol>
        <protons>1</protons>
        <electrons>1</electrons>
        <neutrons>0</neutrons>
        <mass>1.008</mass>
        <valence>1</valence>
    </element>
    <element number="2">
        <name>Helium</name>
        <symbol>He</symbol>
        <protons>2</protons>
        <electrons>2</electrons>
        <neutrons>2</neutrons>
        <mass>4.003</mass>
        <valence>2</valence>
    </element>
    <element number="3">
        <name>Lithium</name>
        <symbol>Li</symbol>
        <protons>3</protons>
        <electrons>3</electrons>
        <neutrons>3</neutrons>
        <mass>6.941</mass>
        <valence>1</valence>
    </element>
    <element number="4">
        <name>Beryllium</name>
        <symbol>Be</symbol>
        <protons>4</protons>
        <electrons>4</electrons>
        <neutrons>5</neutrons>
        <mass>9.021</mass>
        <valence>2</valence>
    </element>
    <element number="5">
        <name>Boron</name>
        <symbol>B</symbol>
        <protons>5</protons>
        <electrons>5</electrons>
        <neutrons>5</neutrons>
        <mass>10.811</mass>
        <valence>3</valence>
    </element>
    <element number="6">
        <name>Carbon</name>
        <symbol>C</symbol>
        <protons>6</protons>
        <electrons>6</electrons>
        <neutrons>6</neutrons>
        <mass>12.01</mass>
        <valence>4</valence>
    </element>
    <element number="7">
        <name>Nitrogen</name>
        <symbol>N</symbol>
        <protons>7</protons>
        <electrons>7</electrons>
        <neutrons>7</neutrons>
        <mass>14.007</mass>
        <valence>5</valence>
    </element>
    <!--
    <element number="">
        <name></name>
        <symbol></symbol>
        <protons></protons>
        <electrons></electrons>
        <neutrons></neutrons>
        <mass></mass>
        <valence></valence>
    </element>
    -->
</elements>